-- Create a newsletter subscription table for Sereya
-- Run this in Supabase SQL editor or via CLI/db query.

CREATE TABLE IF NOT EXISTS public.newsletter_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.newsletter_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts for newsletter subscriptions"
  ON public.newsletter_subscriptions
  FOR INSERT
  WITH CHECK (true);
