-- Create a waitlist table for Sereya
-- Run this in Supabase SQL editor or via CLI/db query.

CREATE TABLE IF NOT EXISTS public.waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts for waitlist"
  ON public.waitlist
  FOR INSERT
  WITH CHECK (true);
